[theme]
primaryColor = "#D4AF37"        # Or (Gold)
backgroundColor = "#f3f0eb"     # Blanc cassé/crème luxe
secondaryBackgroundColor = "#dfd9cf"  # Beige doux
textColor = "#2e2e2e"           # Gris anthracite élégant
font = "serif"                  # Look raffiné (Georgia, Garamond selon système)


[client]
toolbarMode = "minimal"  # Retire les boutons de dev en haut à droite
